# Generated by Django 4.2.13 on 2024-06-22 10:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Tasl',
            new_name='Task',
        ),
    ]
